# Generated by Django 5.1.4 on 2024-12-09 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_company_alter_project_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 9, 20, 59, 55, 898231, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
